frr version 10.2.1
frr defaults traditional
hostname as65002
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65002
 bgp router-id 10.0.12.3
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 timers bgp 3 9
 !
 neighbor 10.0.12.2 remote-as 65001
 neighbor 10.0.12.2 description Peering-to-AS65001
 !
 neighbor 10.0.23.3 remote-as 65003
 neighbor 10.0.23.3 description Peering-to-AS65003
 !
 address-family ipv4 unicast
  neighbor 10.0.12.2 activate
  neighbor 10.0.23.3 activate
 exit-address-family
exit
!
line vty
exit
