frr version 10.2.1
frr defaults traditional
hostname as65004
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65004
 bgp router-id 10.0.34.3
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 timers bgp 3 9
 !
 neighbor 10.0.34.2 remote-as 65003
 neighbor 10.0.34.2 description Peering-to-AS65003
 !
 address-family ipv4 unicast
  neighbor 10.0.34.2 activate
 exit-address-family
exit
!
line vty
exit
