frr version 10.2.1
frr defaults traditional
hostname as65003
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65003
 bgp router-id 10.0.23.3
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 timers bgp 3 9
 !
 neighbor 10.0.23.2 remote-as 65002
 neighbor 10.0.23.2 description Peering-to-AS65002-Transit
 !
 neighbor 10.0.34.3 remote-as 65004
 neighbor 10.0.34.3 description Peering-to-AS65004-Adversary
 !
 address-family ipv4 unicast
  neighbor 10.0.23.2 activate
  neighbor 10.0.23.2 route-map RM_IN_AS65002 in
  neighbor 10.0.23.2 send-community both
  neighbor 10.0.34.3 activate
  neighbor 10.0.34.3 route-map RM_IN_AS65004 in
  neighbor 10.0.34.3 send-community both
 exit-address-family
exit
!
! Standard baseline route-map with default Local Preference 100
route-map RM_IN_AS65002 permit 10
 set local-preference 100
exit
!
route-map RM_IN_AS65004 permit 10
 set local-preference 100
exit
!
line vty
exit
